# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CISM Variational Fracture with FEniCSx
author: Jack S. Hale, Laura de Lorenzis, Corrado Maurini
logo: images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

  # Set timeout for any example to 20 minutes
  timeout: 1800

# Information about where the book exists on the web
repository:
  url: https://newfrac.github.io/fenicsx-fracture/ # Online location of your book
  path_to_book: . # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: "github"
      repository_url: "https://github.com/jhale/cism-varfrac-code"
    html_last_updated_fmt: "%b %d, %Y"

html:
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false
