# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CISM Variational Fracture with FEniCSx
author: Jack S. Hale, Laura de Lorenzis, Corrado Maurini
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 180

# Information about where the book exists on the web
repository:
  url: https://github.com/jhale/cism-2024-varfrac-code/ # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)
html:
  use_repository_button: true
  use_edit_page_button: true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: "github"
      repository_url: "https://github.com/jhale/cism-varfrac-code"
    html_last_updated_fmt: "%b %d, %Y"
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py

html:
  use_issues_button: false
  use_repository_button: false
  use_edit_page_button: false
